def appName="${APP_NAME}"
def project=""

node {
    stage("Initialize") {
        project = env.PROJECT_NAME
    }
}

node("maven") {
    stage("Checkout") {
        git url: "${GIT_SOURCE_URL}", branch: "${GIT_SOURCE_REF}"
    }
    stage("Build WAR") {
        sh "mvn clean package -Popenshift"
        stash name:"war", includes:"target/ROOT.war"
    }
}

node {
    stage("Build Image") {
        unstash name:"war"
        sh "oc start-build ${appName}-docker --from-file=target/ROOT.war --follow -n ${project}"
    }
    stage("Deploy") {
        openshiftDeploy deploymentConfig: appName, namespace: project
    }
}